# Generated by Django 4.1.1 on 2022-09-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=250)),
                ('school', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=250)),
                ('univercity', models.CharField(max_length=250)),
                ('skill', models.CharField(max_length=2000)),
                ('about_you', models.CharField(max_length=2000)),
                ('Previous_works', models.CharField(max_length=2000)),
            ],
        ),
    ]
